import type { Command, Query, DomainEvent, Instant, TenantId } from '../shared-kernel';
import type { CategoryId, CatalogId, ModifierGroupId, ModifierId, ProductId, ProductVariantId, TagId } from './catalog.types';
import type { Barcode, ProductDescription, ProductName, SKU, Slug, Visibility } from './catalog.value-objects';
export type CatalogEventName = 'ProductCreated' | 'ProductUpdated' | 'ProductArchived' | 'ProductPublished' | 'CategoryCreated' | 'CategoryMoved' | 'ModifierGroupCreated' | 'ModifierAttached' | 'ModifierDetached' | 'VisibilityChanged';
/** Events are serializable facts; branded identifiers are represented by their immutable string values. */
export type CatalogEventPayload = Readonly<Record<string, string>> & { readonly catalogId: string; readonly tenantId: string; readonly aggregateId: string; readonly occurredAt: string; };
export type CatalogDomainEvent = DomainEvent<CatalogEventName, CatalogEventPayload>;
export type CreateProduct = Command<'CATALOG_CREATE_PRODUCT', { readonly catalogId: CatalogId; readonly productId: ProductId; readonly name: ProductName; readonly sku: SKU; readonly description?: ProductDescription; readonly slug?: Slug; readonly barcode?: Barcode; }>;
export type UpdateProduct = Command<'CATALOG_UPDATE_PRODUCT', { readonly productId: ProductId; readonly name?: ProductName; readonly description?: ProductDescription; }>;
export type ArchiveProduct = Command<'CATALOG_ARCHIVE_PRODUCT', { readonly productId: ProductId; }>; export type PublishProduct = Command<'CATALOG_PUBLISH_PRODUCT', { readonly productId: ProductId; }>; export type RenameProduct = Command<'CATALOG_RENAME_PRODUCT', { readonly productId: ProductId; readonly name: ProductName; }>; export type ChangeVisibility = Command<'CATALOG_CHANGE_VISIBILITY', { readonly productId: ProductId; readonly visibility: Visibility; }>;
export type CreateCategory = Command<'CATALOG_CREATE_CATEGORY', { readonly catalogId: CatalogId; readonly categoryId: CategoryId; readonly name: ProductName; readonly parentId?: CategoryId; }>; export type MoveCategory = Command<'CATALOG_MOVE_CATEGORY', { readonly categoryId: CategoryId; readonly parentId?: CategoryId; }>;
export type CreateModifierGroup = Command<'CATALOG_CREATE_MODIFIER_GROUP', { readonly catalogId: CatalogId; readonly modifierGroupId: ModifierGroupId; readonly name: ProductName; }>; export type AttachModifier = Command<'CATALOG_ATTACH_MODIFIER', { readonly modifierGroupId: ModifierGroupId; readonly modifierId: ModifierId; readonly name: ProductName; }>; export type DetachModifier = Command<'CATALOG_DETACH_MODIFIER', { readonly modifierGroupId: ModifierGroupId; readonly modifierId: ModifierId; }>;
export type ProductDetailsQuery = Query<'CATALOG_PRODUCT_DETAILS', { readonly productId: ProductId }>; export type CatalogTreeQuery = Query<'CATALOG_TREE', { readonly catalogId: CatalogId }>; export type CategoryListingQuery = Query<'CATALOG_CATEGORY_LIST', { readonly catalogId: CatalogId; readonly parentId?: CategoryId }>; export type ModifierLookupQuery = Query<'CATALOG_MODIFIER_LOOKUP', { readonly modifierGroupId: ModifierGroupId; readonly modifierId?: ModifierId }>; export type ProductSearchQuery = Query<'CATALOG_PRODUCT_SEARCH', { readonly catalogId: CatalogId; readonly term: string }>; export type PublishedCatalogQuery = Query<'CATALOG_PUBLISHED', { readonly catalogId: CatalogId }>;
export interface ProductDetailsReadModel { readonly productId: ProductId; readonly status: string; readonly visibility: Visibility; readonly variantIds: readonly ProductVariantId[]; readonly tagIds: readonly TagId[]; }
