import { ContractError, ValueObject, type AggregateId } from '../shared-kernel';
import type { CategoryId } from './catalog.types';

const text = (value: string, field: string, maximum: number): string => { const normalized = value.trim(); if (normalized.length === 0 || normalized.length > maximum) throw new ContractError('CATALOG_TEXT_INVALID', `${field} must contain 1-${maximum} characters`, { field }); return normalized; };
export class ProductName extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): ProductName { return new ProductName(text(value, 'ProductName', 160)); } }
export class ProductDescription extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): ProductDescription { return new ProductDescription(text(value, 'ProductDescription', 4_000)); } }
export class SKU extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): SKU { const normalized = value.trim().toUpperCase(); if (!/^[A-Z0-9][A-Z0-9._-]{0,63}$/.test(normalized)) throw new ContractError('CATALOG_SKU_INVALID', 'SKU must contain 1-64 uppercase safe characters'); return new SKU(normalized); } }
export class Barcode extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): Barcode { const normalized = value.trim(); if (!/^[0-9A-Za-z-]{4,64}$/.test(normalized)) throw new ContractError('CATALOG_BARCODE_INVALID', 'Barcode must contain 4-64 alphanumeric characters'); return new Barcode(normalized); } }
export class Slug extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): Slug { const normalized = value.trim().toLowerCase(); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(normalized) || normalized.length > 160) throw new ContractError('CATALOG_SLUG_INVALID', 'Slug must be lowercase kebab-case up to 160 characters'); return new Slug(normalized); } }
export class TagName extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): TagName { return new TagName(text(value, 'TagName', 80)); } }
export class DisplayOrder extends ValueObject<{ readonly value: number }> { private constructor(public readonly value: number) { super({ value }); this.freezeValueObject(); } static from(value: number): DisplayOrder { if (!Number.isSafeInteger(value) || value < 0) throw new ContractError('CATALOG_DISPLAY_ORDER_INVALID', 'Display order must be a non-negative safe integer'); return new DisplayOrder(value); } }
export class MediaReference extends ValueObject<{ readonly uri: string; readonly altText?: string }> { private constructor(public readonly uri: string, public readonly altText?: string) { super({ uri, ...(altText === undefined ? {} : { altText }) }); this.freezeValueObject(); } static from(uri: string, altText?: string): MediaReference { const normalizedUri = uri.trim(); if (!/^https?:\/\/.+/.test(normalizedUri)) throw new ContractError('CATALOG_MEDIA_URI_INVALID', 'Media reference must be an absolute HTTP(S) URI'); return new MediaReference(normalizedUri, altText === undefined ? undefined : text(altText, 'MediaAltText', 240)); } }
export class CategoryPath extends ValueObject<{ readonly categoryIds: readonly string[] }> { private constructor(public readonly categoryIds: readonly CategoryId[]) { super({ categoryIds: [...categoryIds] }); this.categoryIds = Object.freeze([...categoryIds]); this.freezeValueObject(); } static from(categoryIds: readonly CategoryId[]): CategoryPath { if (categoryIds.length === 0) throw new ContractError('CATALOG_CATEGORY_PATH_EMPTY', 'Category path must contain at least one category'); if (new Set(categoryIds).size !== categoryIds.length) throw new ContractError('CATALOG_CATEGORY_PATH_CYCLIC', 'Category path cannot contain a category more than once'); return new CategoryPath(categoryIds); } contains(category: CategoryId): boolean { return this.categoryIds.includes(category); } }
export type ProductStatusValue = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED'; export type VisibilityValue = 'VISIBLE' | 'HIDDEN';
export class ProductStatus extends ValueObject<{ readonly value: ProductStatusValue }> { private constructor(public readonly value: ProductStatusValue) { super({ value }); this.freezeValueObject(); } static from(value: string): ProductStatus { if (value !== 'DRAFT' && value !== 'PUBLISHED' && value !== 'ARCHIVED') throw new ContractError('CATALOG_PRODUCT_STATUS_INVALID', 'Invalid product status'); return new ProductStatus(value); } static draft(): ProductStatus { return ProductStatus.from('DRAFT'); } static published(): ProductStatus { return ProductStatus.from('PUBLISHED'); } static archived(): ProductStatus { return ProductStatus.from('ARCHIVED'); } }
export class Visibility extends ValueObject<{ readonly value: VisibilityValue }> { private constructor(public readonly value: VisibilityValue) { super({ value }); this.freezeValueObject(); } static from(value: string): Visibility { if (value !== 'VISIBLE' && value !== 'HIDDEN') throw new ContractError('CATALOG_VISIBILITY_INVALID', 'Invalid product visibility'); return new Visibility(value); } static visible(): Visibility { return Visibility.from('VISIBLE'); } static hidden(): Visibility { return Visibility.from('HIDDEN'); } }
export type CatalogAggregateId = AggregateId<string>;
