import { ContractError, Decimal, ValueObject, type Instant } from '../shared-kernel';

const tokenText = (value: string, code: string): string => { const normalized = value.trim(); if (!/^[A-Za-z0-9._:-]{1,128}$/.test(normalized)) throw new ContractError(code, 'Value is invalid'); return normalized; };
export type ReservationStatusValue = 'REQUESTED' | 'AUTHORIZED' | 'CONFIRMED' | 'RELEASED' | 'CANCELLED' | 'EXPIRED';
export class ReservationStatus extends ValueObject<{ readonly value: ReservationStatusValue }> { private constructor(public readonly value: ReservationStatusValue) { super({ value }); this.freezeValueObject(); } static from(value: string): ReservationStatus { if (value !== 'REQUESTED' && value !== 'AUTHORIZED' && value !== 'CONFIRMED' && value !== 'RELEASED' && value !== 'CANCELLED' && value !== 'EXPIRED') throw new ContractError('RESERVATION_STATUS_INVALID', 'Reservation status is invalid'); return new ReservationStatus(value); } }
export class ReservationReason extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): ReservationReason { const normalized = value.trim(); if (normalized.length === 0 || normalized.length > 240) throw new ContractError('RESERVATION_REASON_INVALID', 'Reservation reason is invalid'); return new ReservationReason(normalized); } }
export class ReservationWindow extends ValueObject<{ readonly startsAt: string; readonly endsAt: string }> { private constructor(public readonly startsAt: Instant, public readonly endsAt: Instant) { super({ startsAt: String(startsAt), endsAt: String(endsAt) }); this.freezeValueObject(); } static from(startsAt: Instant, endsAt: Instant): ReservationWindow { if (String(endsAt) < String(startsAt)) throw new ContractError('RESERVATION_WINDOW_INVALID', 'Reservation window end must not precede start'); return new ReservationWindow(startsAt, endsAt); } includes(at: Instant): boolean { return String(at) >= String(this.startsAt) && String(at) <= String(this.endsAt); } }
export class ReservationExpiry extends ValueObject<{ readonly at: string }> { private constructor(public readonly at: Instant) { super({ at: String(at) }); this.freezeValueObject(); } static at(value: Instant): ReservationExpiry { return new ReservationExpiry(value); } isExpired(at: Instant): boolean { return String(at) >= String(this.at); } }
export class ReservationToken extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): ReservationToken { return new ReservationToken(tokenText(value, 'RESERVATION_TOKEN_INVALID')); } }
export class ReservationReference extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): ReservationReference { return new ReservationReference(tokenText(value, 'RESERVATION_REFERENCE_INVALID')); } }
export class ReservationQuantity extends ValueObject<{ readonly value: string; readonly unit: string }> { private constructor(public readonly value: string, public readonly unit: string) { super({ value, unit }); this.freezeValueObject(); } static from(value: string, unit: string): ReservationQuantity { const amount = Decimal.from(value); const normalizedUnit = unit.trim().toUpperCase(); if (amount.isZero() || amount.isNegative() || !/^[A-Z][A-Z0-9_-]{0,31}$/.test(normalizedUnit)) throw new ContractError('RESERVATION_QUANTITY_INVALID', 'Reservation quantity must be positive with a valid unit'); return new ReservationQuantity(amount.toString(), normalizedUnit); } decimal(): Decimal { return Decimal.from(this.value); } }
