import { ContractError, Decimal, ValueObject, type Instant } from '../shared-kernel';
const checked = (value: string, code: string): string => { const normalized = value.trim(); if (!/^[A-Za-z0-9._:-]{1,128}$/.test(normalized)) throw new ContractError(code, 'Value is invalid'); return normalized; };
export type OrderStatusValue = 'CREATED' | 'VALIDATED' | 'AVAILABILITY_REQUESTED' | 'RESERVATION_AUTHORIZED' | 'CONFIRMED' | 'CANCELLED' | 'EXPIRED';
export class OrderStatus extends ValueObject<{ readonly value: OrderStatusValue }> { private constructor(public readonly value: OrderStatusValue) { super({ value }); this.freezeValueObject(); } static from(value: string): OrderStatus { if (value !== 'CREATED' && value !== 'VALIDATED' && value !== 'AVAILABILITY_REQUESTED' && value !== 'RESERVATION_AUTHORIZED' && value !== 'CONFIRMED' && value !== 'CANCELLED' && value !== 'EXPIRED') throw new ContractError('COMMERCE_ORDER_STATUS_INVALID', 'Order status is invalid'); return new OrderStatus(value); } }
export class OrderReference extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): OrderReference { return new OrderReference(checked(value, 'COMMERCE_ORDER_REFERENCE_INVALID')); } }
export type OrderSourceValue = 'POS' | 'QR' | 'TELEGRAM' | 'MARKETPLACE' | 'API';
export class OrderSource extends ValueObject<{ readonly value: OrderSourceValue }> { private constructor(public readonly value: OrderSourceValue) { super({ value }); this.freezeValueObject(); } static from(value: string): OrderSource { if (value !== 'POS' && value !== 'QR' && value !== 'TELEGRAM' && value !== 'MARKETPLACE' && value !== 'API') throw new ContractError('COMMERCE_ORDER_SOURCE_INVALID', 'Order source is invalid'); return new OrderSource(value); } }
export class OrderChannel extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): OrderChannel { return new OrderChannel(checked(value, 'COMMERCE_ORDER_CHANNEL_INVALID')); } }
export class CustomerIntent extends ValueObject<{ readonly quantity: string; readonly unit: string }> { private constructor(public readonly quantity: string, public readonly unit: string) { super({ quantity, unit }); this.freezeValueObject(); } static from(quantity: string, unit: string): CustomerIntent { const decimal = Decimal.from(quantity); const normalized = unit.trim().toUpperCase(); if (decimal.isZero() || decimal.isNegative() || !/^[A-Z][A-Z0-9_-]{0,31}$/.test(normalized)) throw new ContractError('COMMERCE_CUSTOMER_INTENT_INVALID', 'Customer intent quantity must be positive with a valid unit'); return new CustomerIntent(decimal.toString(), normalized); } decimal(): Decimal { return Decimal.from(this.quantity); } }
export class CheckoutToken extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): CheckoutToken { return new CheckoutToken(checked(value, 'COMMERCE_CHECKOUT_TOKEN_INVALID')); } }
export class CheckoutExpiry extends ValueObject<{ readonly at: string }> { private constructor(public readonly at: Instant) { super({ at: String(at) }); this.freezeValueObject(); } static at(value: Instant): CheckoutExpiry { return new CheckoutExpiry(value); } isExpired(at: Instant): boolean { return String(at) >= String(this.at); } }
