import { AggregateRoot, Entity, type Instant, type TenantId } from '../shared-kernel';
import type { ProductId } from '../catalog-domain';
import type { ResolvedPrice } from '../pricing-domain';
import type { PromiseDecision } from '../availability';
import type { ReservationId } from '../reservation';
import type { CommerceDomainEvent, CommerceEventName, OrderSnapshot } from './commerce.contracts';
import { commerceInvariant } from './commerce.errors';
import type { CheckoutId, OrderId } from './commerce.types';
import { CheckoutExpiry, CheckoutToken, CustomerIntent, OrderChannel, OrderReference, OrderSource, OrderStatus } from './commerce.value-objects';

const event = (name: CommerceEventName, tenantId: TenantId, orderId: OrderId, occurredAt: Instant): CommerceDomainEvent => ({ name, payload: { tenantId: String(tenantId), orderId: String(orderId), occurredAt: String(occurredAt) } });
export class OrderIntent extends Entity<OrderId> { constructor(id: OrderId, public readonly productId: ProductId, public readonly customerIntent: CustomerIntent, public readonly reference: OrderReference, public readonly source: OrderSource, public readonly channel: OrderChannel) { super(id); Object.freeze(this); } }
export class OrderLifecycle extends Entity<OrderId> { constructor(id: OrderId, public readonly status: OrderStatus) { super(id); Object.freeze(this); } }
export class CheckoutSession extends AggregateRoot<CheckoutId, CommerceDomainEvent> { private expiredValue = false; private constructor(public readonly tenantId: TenantId, id: CheckoutId, public readonly token: CheckoutToken, public readonly expiry: CheckoutExpiry) { super(id); } static create(tenantId: TenantId, id: CheckoutId, token: CheckoutToken, expiry: CheckoutExpiry): CheckoutSession { return new CheckoutSession(tenantId, id, token, expiry); } get expired(): boolean { return this.expiredValue; } expire(at: Instant): void { if (!this.expiry.isExpired(at)) commerceInvariant('COMMERCE_CHECKOUT_NOT_EXPIRED', 'Checkout expiry has not been reached'); this.expiredValue = true; this.incrementVersion(); } }

export class CustomerOrder extends AggregateRoot<OrderId, CommerceDomainEvent> {
  private statusValue = OrderStatus.from('CREATED'); private priceValue?: ResolvedPrice; private reservationIdValue?: ReservationId;
  private constructor(public readonly tenantId: TenantId, id: OrderId, public readonly checkoutId: CheckoutId, public readonly intent: OrderIntent, public readonly checkout: CheckoutSession) { super(id); }
  static create(tenantId: TenantId, id: OrderId, checkoutId: CheckoutId, intent: OrderIntent, checkout: CheckoutSession, at: Instant): CustomerOrder { const order = new CustomerOrder(tenantId, id, checkoutId, intent, checkout); order.record(event('OrderCreated', tenantId, id, at)); return order; }
  get status(): OrderStatus { return this.statusValue; } get price(): ResolvedPrice | undefined { return this.priceValue; } get reservationId(): ReservationId | undefined { return this.reservationIdValue; }
  validate(price: ResolvedPrice, at: Instant): void { this.assertStatus('CREATED'); this.assertCheckout(at); if (price.productId !== this.intent.productId) commerceInvariant('COMMERCE_PRICE_PRODUCT_MISMATCH', 'Price snapshot must match order product'); this.priceValue = Object.freeze({ ...price, discounts: Object.freeze([...price.discounts]), taxes: Object.freeze([...price.taxes]), serviceCharges: Object.freeze([...price.serviceCharges]), trace: Object.freeze([...price.trace]) }); this.statusValue = OrderStatus.from('VALIDATED'); this.incrementVersion(); this.record(event('OrderValidated', this.tenantId, this.id, at)); }
  requestAvailability(at: Instant): void { this.assertStatus('VALIDATED'); this.assertCheckout(at); this.statusValue = OrderStatus.from('AVAILABILITY_REQUESTED'); this.incrementVersion(); this.record(event('AvailabilityRequested', this.tenantId, this.id, at)); }
  authorizeReservation(reservationId: ReservationId, decision: PromiseDecision, at: Instant): void { this.assertStatus('AVAILABILITY_REQUESTED'); this.assertCheckout(at); if (!decision.canPromise || decision.capacity.unit !== this.intent.customerIntent.unit || decision.capacity.decimal().compare(this.intent.customerIntent.decimal()) < 0) commerceInvariant('COMMERCE_RESERVATION_NOT_AUTHORIZED', 'Reservation authorization does not cover order intent'); this.reservationIdValue = reservationId; this.statusValue = OrderStatus.from('RESERVATION_AUTHORIZED'); this.incrementVersion(); this.record(event('ReservationAuthorized', this.tenantId, this.id, at)); }
  finalize(at: Instant): void { this.assertStatus('RESERVATION_AUTHORIZED'); this.assertCheckout(at); this.statusValue = OrderStatus.from('CONFIRMED'); this.incrementVersion(); this.record(event('OrderConfirmed', this.tenantId, this.id, at)); }
  cancel(at: Instant): void { if (this.statusValue.value === 'CANCELLED' || this.statusValue.value === 'CONFIRMED' || this.statusValue.value === 'EXPIRED') commerceInvariant('COMMERCE_ORDER_TERMINAL', 'Terminal order cannot be cancelled'); this.statusValue = OrderStatus.from('CANCELLED'); this.incrementVersion(); this.record(event('OrderCancelled', this.tenantId, this.id, at)); }
  expire(at: Instant): void { if (this.statusValue.value === 'CONFIRMED' || this.statusValue.value === 'CANCELLED' || this.statusValue.value === 'EXPIRED') commerceInvariant('COMMERCE_ORDER_TERMINAL', 'Terminal order cannot expire'); if (!this.checkout.expiry.isExpired(at)) commerceInvariant('COMMERCE_CHECKOUT_NOT_EXPIRED', 'Checkout expiry has not been reached'); this.statusValue = OrderStatus.from('EXPIRED'); this.incrementVersion(); this.record(event('CheckoutExpired', this.tenantId, this.id, at)); }
  snapshot(): OrderSnapshot { return Object.freeze({ orderId: this.id, checkoutId: this.checkoutId, productId: this.intent.productId, ...(this.priceValue === undefined ? {} : { price: this.priceValue }), ...(this.reservationIdValue === undefined ? {} : { reservationId: this.reservationIdValue }), status: this.statusValue.value, version: Number(this.version) }); }
  private assertStatus(expected: OrderStatus['value']): void { if (this.statusValue.value !== expected) commerceInvariant('COMMERCE_ORDER_TRANSITION_ILLEGAL', `Order transition requires ${expected}`); }
  private assertCheckout(at: Instant): void { if (this.checkout.expired || this.checkout.expiry.isExpired(at)) { this.statusValue = OrderStatus.from('EXPIRED'); this.incrementVersion(); this.record(event('CheckoutExpired', this.tenantId, this.id, at)); commerceInvariant('COMMERCE_CHECKOUT_EXPIRED', 'Checkout has expired'); } }
}
