import { ContractError, Decimal, ValueObject } from '../shared-kernel';

const text = (value: string, code: string, maximum = 160): string => { const normalized = value.trim(); if (normalized.length === 0 || normalized.length > maximum) throw new ContractError(code, 'Value must not be empty or exceed its maximum length'); return normalized; };
const positive = (value: string): string => { const decimal = Decimal.from(value); if (decimal.isNegative() || decimal.isZero()) throw new ContractError('LEDGER_MOVEMENT_QUANTITY_INVALID', 'Movement quantity must be positive'); return decimal.toString(); };

export class MovementQuantity extends ValueObject<{ readonly value: string; readonly unit: string }> {
  private constructor(public readonly value: string, public readonly unit: string) { super({ value, unit }); this.freezeValueObject(); }
  static from(value: string, unit: string): MovementQuantity { const normalizedUnit = text(unit, 'LEDGER_MOVEMENT_UNIT_INVALID', 32).toUpperCase(); if (!/^[A-Z][A-Z0-9_-]{0,31}$/.test(normalizedUnit)) throw new ContractError('LEDGER_MOVEMENT_UNIT_INVALID', 'Movement unit is invalid'); return new MovementQuantity(positive(value), normalizedUnit); }
  decimal(): Decimal { return Decimal.from(this.value); }
}
export class MovementReason extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): MovementReason { return new MovementReason(text(value, 'LEDGER_MOVEMENT_REASON_INVALID', 240)); } }
export class LedgerReference extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): LedgerReference { return new LedgerReference(text(value, 'LEDGER_REFERENCE_INVALID', 128)); } }
export type TransactionTypeValue = 'RECEIPT' | 'CONSUMPTION' | 'WASTE' | 'ADJUSTMENT' | 'TRANSFER_OUT' | 'TRANSFER_IN' | 'RESERVATION_HOLD' | 'RESERVATION_RELEASE' | 'CORRECTION';
export class TransactionType extends ValueObject<{ readonly value: TransactionTypeValue }> { private constructor(public readonly value: TransactionTypeValue) { super({ value }); this.freezeValueObject(); } static from(value: string): TransactionType { const allowed: readonly TransactionTypeValue[] = ['RECEIPT', 'CONSUMPTION', 'WASTE', 'ADJUSTMENT', 'TRANSFER_OUT', 'TRANSFER_IN', 'RESERVATION_HOLD', 'RESERVATION_RELEASE', 'CORRECTION']; if (!allowed.includes(value as TransactionTypeValue)) throw new ContractError('LEDGER_TRANSACTION_TYPE_INVALID', 'Transaction type is invalid'); return new TransactionType(value as TransactionTypeValue); } }
export type MovementDirectionValue = 'IN' | 'OUT' | 'HOLD' | 'RELEASE';
export class MovementDirection extends ValueObject<{ readonly value: MovementDirectionValue }> { private constructor(public readonly value: MovementDirectionValue) { super({ value }); this.freezeValueObject(); } static from(value: string): MovementDirection { if (value !== 'IN' && value !== 'OUT' && value !== 'HOLD' && value !== 'RELEASE') throw new ContractError('LEDGER_MOVEMENT_DIRECTION_INVALID', 'Movement direction is invalid'); return new MovementDirection(value); } }
export class AdjustmentReason extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): AdjustmentReason { return new AdjustmentReason(text(value, 'LEDGER_ADJUSTMENT_REASON_INVALID', 240)); } }
export class TransferReference extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): TransferReference { return new TransferReference(text(value, 'LEDGER_TRANSFER_REFERENCE_INVALID', 128)); } }
export class ReservationReference extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): ReservationReference { return new ReservationReference(text(value, 'LEDGER_RESERVATION_REFERENCE_INVALID', 128)); } }
export class SnapshotVersion extends ValueObject<{ readonly value: number }> { private constructor(public readonly value: number) { super({ value }); this.freezeValueObject(); } static from(value: number): SnapshotVersion { if (!Number.isSafeInteger(value) || value < 0) throw new ContractError('LEDGER_SNAPSHOT_VERSION_INVALID', 'Snapshot version must be a non-negative safe integer'); return new SnapshotVersion(value); } }
export class LedgerSequence extends ValueObject<{ readonly value: number }> { private constructor(public readonly value: number) { super({ value }); this.freezeValueObject(); } static from(value: number): LedgerSequence { if (!Number.isSafeInteger(value) || value < 1) throw new ContractError('LEDGER_SEQUENCE_INVALID', 'Ledger sequence must be a positive safe integer'); return new LedgerSequence(value); } }
