import { AggregateRoot, Entity, type Instant, type TenantId } from '../shared-kernel';
import type { InventoryItemId, StorageLocationId } from '../inventory-core';
import type { InventoryLedgerDomainEvent, InventoryLedgerEventName } from './inventory-ledger.contracts';
import { ledgerInvariant } from './inventory-ledger.errors';
import type { InventoryLedgerId, LedgerEntryId, ReservationHoldId, TransferId } from './inventory-ledger.types';
import { AdjustmentReason, LedgerReference, LedgerSequence, MovementDirection, MovementQuantity, MovementReason, ReservationReference, SnapshotVersion, TransactionType, TransferReference } from './inventory-ledger.value-objects';

const event = (name: InventoryLedgerEventName, tenantId: TenantId, ledgerId: InventoryLedgerId, entryId: LedgerEntryId, occurredAt: Instant): InventoryLedgerDomainEvent => ({ name, payload: { tenantId: String(tenantId), ledgerId: String(ledgerId), entryId: String(entryId), occurredAt: String(occurredAt) } });

export class LedgerEntry extends Entity<LedgerEntryId> {
  constructor(id: LedgerEntryId, public readonly sequence: LedgerSequence, public readonly type: TransactionType, public readonly direction: MovementDirection, public readonly quantity: MovementQuantity, public readonly reason: MovementReason, public readonly occurredAt: Instant, public readonly reference?: LedgerReference, public readonly correctionOf?: LedgerEntryId) { super(id); Object.freeze(this); }
}
export class ReservationHold extends Entity<ReservationHoldId> { constructor(id: ReservationHoldId, public readonly entryId: LedgerEntryId, public readonly reference: ReservationReference, public readonly quantity: MovementQuantity) { super(id); Object.freeze(this); } }
export class ReservationRelease extends Entity<LedgerEntryId> { constructor(id: LedgerEntryId, public readonly holdId: ReservationHoldId, public readonly entryId: LedgerEntryId, public readonly reference: ReservationReference, public readonly quantity: MovementQuantity) { super(id); Object.freeze(this); } }
export class StockAdjustment extends Entity<LedgerEntryId> { constructor(id: LedgerEntryId, public readonly entryId: LedgerEntryId, public readonly reason: AdjustmentReason) { super(id); Object.freeze(this); } }
export class Transfer extends Entity<TransferId> { constructor(id: TransferId, public readonly entryId: LedgerEntryId, public readonly reference: TransferReference, public readonly destinationLocationId: StorageLocationId) { super(id); Object.freeze(this); } }
export class Receipt extends Entity<LedgerEntryId> { constructor(id: LedgerEntryId, public readonly entryId: LedgerEntryId, public readonly reference: LedgerReference) { super(id); Object.freeze(this); } }
export class WasteEntry extends Entity<LedgerEntryId> { constructor(id: LedgerEntryId, public readonly entryId: LedgerEntryId) { super(id); Object.freeze(this); } }
export class ConsumptionEntry extends Entity<LedgerEntryId> { constructor(id: LedgerEntryId, public readonly entryId: LedgerEntryId) { super(id); Object.freeze(this); } }

export class InventoryLedger extends AggregateRoot<InventoryLedgerId, InventoryLedgerDomainEvent> {
  private readonly entriesValue: LedgerEntry[] = [];
  private readonly holdsValue: ReservationHold[] = [];
  private readonly releasesValue: ReservationRelease[] = [];
  private sequence = 0;
  private constructor(public readonly tenantId: TenantId, id: InventoryLedgerId, public readonly inventoryItemId: InventoryItemId, public readonly storageLocationId: StorageLocationId, public readonly unit: string) { super(id); }
  static create(tenantId: TenantId, id: InventoryLedgerId, itemId: InventoryItemId, locationId: StorageLocationId, unit: string): InventoryLedger { return new InventoryLedger(tenantId, id, itemId, locationId, unit.trim().toUpperCase()); }
  get entries(): readonly LedgerEntry[] { return Object.freeze([...this.entriesValue]); }
  get reservationHolds(): readonly ReservationHold[] { return Object.freeze([...this.holdsValue]); }
  get reservationReleases(): readonly ReservationRelease[] { return Object.freeze([...this.releasesValue]); }

  receive(entryId: LedgerEntryId, quantity: MovementQuantity, reference: LedgerReference, reason: MovementReason, occurredAt: Instant): Receipt { const entry = this.append(entryId, 'RECEIPT', 'IN', quantity, reason, occurredAt, reference); this.record(event('StockReceived', this.tenantId, this.id, entryId, occurredAt)); return new Receipt(entryId, entry.id, reference); }
  consume(entryId: LedgerEntryId, quantity: MovementQuantity, reason: MovementReason, occurredAt: Instant, allowNegative = false): ConsumptionEntry { if (!allowNegative && this.availableQuantity() < this.amount(quantity)) ledgerInvariant('LEDGER_INSUFFICIENT_AVAILABLE_STOCK', 'Consumption exceeds available stock'); const entry = this.append(entryId, 'CONSUMPTION', 'OUT', quantity, reason, occurredAt); this.record(event('StockConsumed', this.tenantId, this.id, entryId, occurredAt)); return new ConsumptionEntry(entryId, entry.id); }
  reserve(holdId: ReservationHoldId, entryId: LedgerEntryId, quantity: MovementQuantity, reference: ReservationReference, occurredAt: Instant): ReservationHold { if (this.availableQuantity() < this.amount(quantity)) ledgerInvariant('LEDGER_INSUFFICIENT_AVAILABLE_STOCK', 'Reservation exceeds available stock'); if (this.holdsValue.some((hold) => hold.id === holdId || hold.reference.equals(reference))) ledgerInvariant('LEDGER_RESERVATION_DUPLICATE', 'Reservation hold already exists'); const entry = this.append(entryId, 'RESERVATION_HOLD', 'HOLD', quantity, MovementReason.from('Reservation hold'), occurredAt); const hold = new ReservationHold(holdId, entry.id, reference, quantity); this.holdsValue.push(hold); this.record(event('StockReserved', this.tenantId, this.id, entryId, occurredAt)); return hold; }
  release(holdId: ReservationHoldId, entryId: LedgerEntryId, quantity: MovementQuantity, reference: ReservationReference, occurredAt: Instant): ReservationRelease { const held = this.holdsValue.find((hold) => hold.id === holdId); if (!held) ledgerInvariant('LEDGER_RESERVATION_HOLD_MISSING', 'Reservation hold does not exist'); if (!held.reference.equals(reference) || this.amount(quantity) > this.amount(held.quantity)) ledgerInvariant('LEDGER_RESERVATION_RELEASE_INVALID', 'Reservation release does not match the held quantity'); const released = this.releasedFor(holdId); if (released + this.amount(quantity) > this.amount(held.quantity)) ledgerInvariant('LEDGER_RESERVATION_OVER_RELEASE', 'Reservation cannot be released more than once'); const entry = this.append(entryId, 'RESERVATION_RELEASE', 'RELEASE', quantity, MovementReason.from('Reservation release'), occurredAt); const release = new ReservationRelease(entryId, holdId, entry.id, reference, quantity); this.releasesValue.push(release); this.record(event('ReservationReleased', this.tenantId, this.id, entryId, occurredAt)); return release; }
  adjust(entryId: LedgerEntryId, quantity: MovementQuantity, reason: AdjustmentReason, increase: boolean, occurredAt: Instant): StockAdjustment { const entry = this.append(entryId, 'ADJUSTMENT', increase ? 'IN' : 'OUT', quantity, MovementReason.from(reason.value), occurredAt); this.record(event('StockAdjusted', this.tenantId, this.id, entryId, occurredAt)); return new StockAdjustment(entryId, entry.id, reason); }
  waste(entryId: LedgerEntryId, quantity: MovementQuantity, reason: MovementReason, occurredAt: Instant): WasteEntry { if (this.availableQuantity() < this.amount(quantity)) ledgerInvariant('LEDGER_INSUFFICIENT_AVAILABLE_STOCK', 'Waste exceeds available stock'); const entry = this.append(entryId, 'WASTE', 'OUT', quantity, reason, occurredAt); this.record(event('WasteRecorded', this.tenantId, this.id, entryId, occurredAt)); return new WasteEntry(entryId, entry.id); }
  transferOut(transferId: TransferId, entryId: LedgerEntryId, quantity: MovementQuantity, reference: TransferReference, destinationLocationId: StorageLocationId, occurredAt: Instant): Transfer { if (destinationLocationId === this.storageLocationId) ledgerInvariant('LEDGER_TRANSFER_LOCATION_INVALID', 'Transfer source and destination must differ'); if (this.availableQuantity() < this.amount(quantity)) ledgerInvariant('LEDGER_INSUFFICIENT_AVAILABLE_STOCK', 'Transfer exceeds available stock'); const entry = this.append(entryId, 'TRANSFER_OUT', 'OUT', quantity, MovementReason.from('Transfer out'), occurredAt, LedgerReference.from(reference.value)); this.record(event('TransferCompleted', this.tenantId, this.id, entryId, occurredAt)); return new Transfer(transferId, entry.id, reference, destinationLocationId); }
  correct(entryId: LedgerEntryId, correctionOf: LedgerEntryId, quantity: MovementQuantity, reason: MovementReason, increase: boolean, occurredAt: Instant): LedgerEntry { if (!this.entriesValue.some((entry) => entry.id === correctionOf)) ledgerInvariant('LEDGER_CORRECTION_REFERENCE_MISSING', 'Correction must reference an earlier movement'); const entry = this.append(entryId, 'CORRECTION', increase ? 'IN' : 'OUT', quantity, reason, occurredAt, undefined, correctionOf); this.record(event('LedgerCorrected', this.tenantId, this.id, entryId, occurredAt)); return entry; }
  snapshot(version: SnapshotVersion): Readonly<{ readonly version: SnapshotVersion; readonly sequence: LedgerSequence; readonly onHand: string; readonly reserved: string; readonly available: string; readonly unit: string }> { return Object.freeze({ version, sequence: LedgerSequence.from(this.sequence || 1), onHand: this.format(this.onHandQuantity()), reserved: this.format(this.reservedQuantity()), available: this.format(this.availableQuantity()), unit: this.unit }); }
  private append(id: LedgerEntryId, type: Parameters<typeof TransactionType.from>[0], direction: Parameters<typeof MovementDirection.from>[0], quantity: MovementQuantity, reason: MovementReason, occurredAt: Instant, reference?: LedgerReference, correctionOf?: LedgerEntryId): LedgerEntry { if (this.entriesValue.some((entry) => entry.id === id)) ledgerInvariant('LEDGER_ENTRY_DUPLICATE', 'Ledger entry is immutable and cannot be recorded twice'); if (quantity.unit !== this.unit) ledgerInvariant('LEDGER_MOVEMENT_UNIT_MISMATCH', 'Movement unit must match ledger unit'); this.sequence += 1; const entry = new LedgerEntry(id, LedgerSequence.from(this.sequence), TransactionType.from(type), MovementDirection.from(direction), quantity, reason, occurredAt, reference, correctionOf); this.entriesValue.push(entry); this.incrementVersion(); return entry; }
  private amount(quantity: MovementQuantity): bigint { return BigInt(quantity.decimal().toFixed(6).replace('.', '')); }
  private onHandQuantity(): bigint { return this.entriesValue.reduce((total, entry) => entry.direction.value === 'IN' ? total + this.amount(entry.quantity) : entry.direction.value === 'OUT' ? total - this.amount(entry.quantity) : total, 0n); }
  private reservedQuantity(): bigint { return this.entriesValue.reduce((total, entry) => entry.direction.value === 'HOLD' ? total + this.amount(entry.quantity) : entry.direction.value === 'RELEASE' ? total - this.amount(entry.quantity) : total, 0n); }
  private availableQuantity(): bigint { return this.onHandQuantity() - this.reservedQuantity(); }
  private releasedFor(holdId: ReservationHoldId): bigint { return this.releasesValue.filter((release) => release.holdId === holdId).reduce((total, release) => total + this.amount(release.quantity), 0n); }
  private format(value: bigint): string { const sign = value < 0n ? '-' : ''; const absolute = value < 0n ? -value : value; return `${sign}${absolute / 1_000_000n}.${(absolute % 1_000_000n).toString().padStart(6, '0')}`.replace(/\.0+$/, '').replace(/(\.\d*?)0+$/, '$1'); }
}
