import { AggregateRoot, Entity, type Instant, type TenantId } from '../shared-kernel';
import type { LedgerStockSnapshot } from '../inventory-ledger';
import type { AvailabilityDomainEvent, AvailabilityEventName, CapacityBreakdown, PromiseDecision } from './availability.contracts';
import { availabilityInvariant } from './availability.errors';
import type { AvailabilitySnapshotId, CapacityFenceId, CapacityPolicyAggregateId, ReservationCapacityAggregateId } from './availability.types';
import { AllocationPolicy, AvailabilityReason, AvailabilityWindow, CapacityFence as CapacityFenceValue, CapacityPolicyId, CapacityState, ReservableQuantity, SafetyBuffer } from './availability.value-objects';

const event = (name: AvailabilityEventName, tenantId: TenantId, snapshotId: AvailabilitySnapshotId, occurredAt: Instant): AvailabilityDomainEvent => ({ name, payload: { tenantId: String(tenantId), snapshotId: String(snapshotId), occurredAt: String(occurredAt) } });

export class CapacityPolicy extends AggregateRoot<CapacityPolicyAggregateId, AvailabilityDomainEvent> {
  private constructor(public readonly tenantId: TenantId, id: CapacityPolicyAggregateId, public readonly policyId: CapacityPolicyId, private safetyBufferValue: SafetyBuffer, private capacityFenceValue: CapacityFenceValue, private allocationPolicyValue: AllocationPolicy, private windowValue: AvailabilityWindow) { super(id); }
  static create(tenantId: TenantId, id: CapacityPolicyAggregateId, policyId: CapacityPolicyId, safetyBuffer: SafetyBuffer, capacityFence: CapacityFenceValue, allocationPolicy: AllocationPolicy, window: AvailabilityWindow): CapacityPolicy { return new CapacityPolicy(tenantId, id, policyId, safetyBuffer, capacityFence, allocationPolicy, window); }
  get safetyBuffer(): SafetyBuffer { return this.safetyBufferValue; } get capacityFence(): CapacityFenceValue { return this.capacityFenceValue; } get allocationPolicy(): AllocationPolicy { return this.allocationPolicyValue; } get window(): AvailabilityWindow { return this.windowValue; }
  update(safetyBuffer: SafetyBuffer, capacityFence: CapacityFenceValue, allocationPolicy: AllocationPolicy, window: AvailabilityWindow, snapshotId: AvailabilitySnapshotId, occurredAt: Instant): void { this.safetyBufferValue = safetyBuffer; this.capacityFenceValue = capacityFence; this.allocationPolicyValue = allocationPolicy; this.windowValue = window; this.incrementVersion(); this.record(event('CapacityPolicyUpdated', this.tenantId, snapshotId, occurredAt)); }
}

export class CapacityFence extends Entity<CapacityFenceId> { constructor(id: CapacityFenceId, public readonly quantity: CapacityFenceValue) { super(id); Object.freeze(this); } }
export class AvailabilityStatus extends Entity<AvailabilitySnapshotId> { constructor(id: AvailabilitySnapshotId, public readonly state: CapacityState, public readonly reason: AvailabilityReason) { super(id); Object.freeze(this); } }
export class ReservationCapacity extends AggregateRoot<ReservationCapacityAggregateId, AvailabilityDomainEvent> { private releasedValue = false; constructor(public readonly tenantId: TenantId, id: ReservationCapacityAggregateId, public readonly snapshotId: AvailabilitySnapshotId, public readonly quantity: ReservableQuantity, occurredAt: Instant) { super(id); this.record(event('CapacityReserved', tenantId, snapshotId, occurredAt)); } get released(): boolean { return this.releasedValue; } release(occurredAt: Instant): void { if (this.releasedValue) availabilityInvariant('AVAILABILITY_CAPACITY_ALREADY_RELEASED', 'Capacity reservation is already released'); this.releasedValue = true; this.incrementVersion(); this.record(event('CapacityReleased', this.tenantId, this.snapshotId, occurredAt)); } }

export class AvailabilitySnapshot extends AggregateRoot<AvailabilitySnapshotId, AvailabilityDomainEvent> {
  private constructor(public readonly tenantId: TenantId, id: AvailabilitySnapshotId, public readonly ledger: LedgerStockSnapshot, public readonly breakdown: CapacityBreakdown, public readonly status: AvailabilityStatus) { super(id); }
  static calculate(tenantId: TenantId, id: AvailabilitySnapshotId, ledger: LedgerStockSnapshot, policy: CapacityPolicy, occurredAt: Instant): AvailabilitySnapshot { const immutableLedger = Object.freeze({ ...ledger }); if (immutableLedger.tenantId !== tenantId || policy.tenantId !== tenantId) availabilityInvariant('AVAILABILITY_TENANT_MISMATCH', 'Availability calculation requires one tenant'); if (!policy.window.includes(occurredAt)) return AvailabilitySnapshot.withState(tenantId, id, immutableLedger, policy, occurredAt, 'WINDOW_CLOSED', 'OUTSIDE_AVAILABILITY_WINDOW'); const onHand = toRaw(immutableLedger.onHandQuantity); const held = toRaw(immutableLedger.reservationHoldQuantity); const buffer = toRaw(policy.safetyBuffer.value); const fence = toRaw(policy.capacityFence.value); const adjustment = toRaw(policy.allocationPolicy.adjustment); if (policy.safetyBuffer.unit !== immutableLedger.unit || policy.capacityFence.unit !== immutableLedger.unit) availabilityInvariant('AVAILABILITY_POLICY_UNIT_MISMATCH', 'Policy quantities must use Ledger unit'); if (buffer > onHand) availabilityInvariant('AVAILABILITY_SAFETY_BUFFER_EXCEEDS_STOCK', 'Safety buffer cannot exceed on-hand quantity'); if (fence > onHand - held) availabilityInvariant('AVAILABILITY_CAPACITY_FENCE_EXCEEDS_STOCK', 'Capacity fence cannot exceed available Ledger stock'); const remaining = onHand - held - buffer - fence - adjustment; return AvailabilitySnapshot.withState(tenantId, id, immutableLedger, policy, occurredAt, remaining > 0n ? 'AVAILABLE' : 'EXHAUSTED', remaining > 0n ? 'AVAILABLE' : 'INSUFFICIENT_CAPACITY'); }
  private static withState(tenantId: TenantId, id: AvailabilitySnapshotId, ledger: LedgerStockSnapshot, policy: CapacityPolicy, occurredAt: Instant, state: 'AVAILABLE' | 'EXHAUSTED' | 'WINDOW_CLOSED', reason: 'AVAILABLE' | 'INSUFFICIENT_CAPACITY' | 'OUTSIDE_AVAILABILITY_WINDOW'): AvailabilitySnapshot { const amount = state === 'WINDOW_CLOSED' ? 0n : maximum(0n, toRaw(ledger.onHandQuantity) - toRaw(ledger.reservationHoldQuantity) - toRaw(policy.safetyBuffer.value) - toRaw(policy.capacityFence.value) - toRaw(policy.allocationPolicy.adjustment)); const breakdown: CapacityBreakdown = Object.freeze({ ledgerSequence: ledger.ledgerSequence, onHandQuantity: ledger.onHandQuantity, reservationHoldQuantity: ledger.reservationHoldQuantity, safetyBuffer: policy.safetyBuffer.value, capacityFence: policy.capacityFence.value, policyAdjustment: policy.allocationPolicy.adjustment, reservableQuantity: format(amount), unit: ledger.unit }); const status = new AvailabilityStatus(id, CapacityState.from(state), AvailabilityReason.from(reason)); const snapshot = new AvailabilitySnapshot(tenantId, id, ledger, breakdown, status); snapshot.record(event('AvailabilityCalculated', tenantId, id, occurredAt)); return snapshot; }
  decide(requested: ReservableQuantity, occurredAt: Instant): PromiseDecision { if (requested.unit !== this.breakdown.unit) availabilityInvariant('AVAILABILITY_REQUEST_UNIT_MISMATCH', 'Requested quantity must use snapshot unit'); if (this.status.state.value === 'WINDOW_CLOSED') return Object.freeze({ canPromise: false, reason: AvailabilityReason.from('OUTSIDE_AVAILABILITY_WINDOW'), capacity: ReservableQuantity.from(this.breakdown.reservableQuantity, this.breakdown.unit) }); const canPromise = requested.decimal().compare(ReservableQuantity.from(this.breakdown.reservableQuantity, this.breakdown.unit).decimal()) <= 0; return Object.freeze({ canPromise, reason: AvailabilityReason.from(canPromise ? 'AVAILABLE' : 'INSUFFICIENT_CAPACITY'), capacity: ReservableQuantity.from(this.breakdown.reservableQuantity, this.breakdown.unit) }); }
}

const toRaw = (value: string): bigint => BigInt(value.includes('.') ? `${value.split('.')[0]}${value.split('.')[1].padEnd(6, '0')}` : `${value}000000`);
const maximum = (left: bigint, right: bigint): bigint => left > right ? left : right;
const format = (value: bigint): string => `${value / 1_000_000n}.${(value % 1_000_000n).toString().padStart(6, '0')}`.replace(/\.0+$/, '').replace(/(\.\d*?)0+$/, '$1');
