import { ContractError, Decimal, ValueObject, type Instant } from '../shared-kernel';

const nonNegative = (value: string, code: string): string => { const decimal = Decimal.from(value); if (decimal.isNegative()) throw new ContractError(code, 'Value cannot be negative'); return decimal.toString(); };
const unit = (value: string): string => { const normalized = value.trim().toUpperCase(); if (!/^[A-Z][A-Z0-9_-]{0,31}$/.test(normalized)) throw new ContractError('AVAILABILITY_UNIT_INVALID', 'Unit is invalid'); return normalized; };

export class ReservableQuantity extends ValueObject<{ readonly value: string; readonly unit: string }> { private constructor(public readonly value: string, public readonly unit: string) { super({ value, unit }); this.freezeValueObject(); } static from(value: string, unitValue: string): ReservableQuantity { return new ReservableQuantity(nonNegative(value, 'AVAILABILITY_RESERVABLE_QUANTITY_INVALID'), unit(unitValue)); } decimal(): Decimal { return Decimal.from(this.value); } }
export class SafetyBuffer extends ValueObject<{ readonly value: string; readonly unit: string }> { private constructor(public readonly value: string, public readonly unit: string) { super({ value, unit }); this.freezeValueObject(); } static from(value: string, unitValue: string): SafetyBuffer { return new SafetyBuffer(nonNegative(value, 'AVAILABILITY_SAFETY_BUFFER_INVALID'), unit(unitValue)); } decimal(): Decimal { return Decimal.from(this.value); } }
export class CapacityFence extends ValueObject<{ readonly value: string; readonly unit: string }> { private constructor(public readonly value: string, public readonly unit: string) { super({ value, unit }); this.freezeValueObject(); } static from(value: string, unitValue: string): CapacityFence { return new CapacityFence(nonNegative(value, 'AVAILABILITY_CAPACITY_FENCE_INVALID'), unit(unitValue)); } decimal(): Decimal { return Decimal.from(this.value); } }
export type AvailabilityReasonValue = 'AVAILABLE' | 'INSUFFICIENT_CAPACITY' | 'OUTSIDE_AVAILABILITY_WINDOW' | 'POLICY_BLOCKED';
export class AvailabilityReason extends ValueObject<{ readonly value: AvailabilityReasonValue }> { private constructor(public readonly value: AvailabilityReasonValue) { super({ value }); this.freezeValueObject(); } static from(value: string): AvailabilityReason { if (value !== 'AVAILABLE' && value !== 'INSUFFICIENT_CAPACITY' && value !== 'OUTSIDE_AVAILABILITY_WINDOW' && value !== 'POLICY_BLOCKED') throw new ContractError('AVAILABILITY_REASON_INVALID', 'Availability reason is invalid'); return new AvailabilityReason(value); } }
export type CapacityStateValue = 'AVAILABLE' | 'EXHAUSTED' | 'WINDOW_CLOSED';
export class CapacityState extends ValueObject<{ readonly value: CapacityStateValue }> { private constructor(public readonly value: CapacityStateValue) { super({ value }); this.freezeValueObject(); } static from(value: string): CapacityState { if (value !== 'AVAILABLE' && value !== 'EXHAUSTED' && value !== 'WINDOW_CLOSED') throw new ContractError('AVAILABILITY_CAPACITY_STATE_INVALID', 'Capacity state is invalid'); return new CapacityState(value); } }
export class CapacityPolicyId extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): CapacityPolicyId { const normalized = value.trim(); if (!/^[A-Za-z0-9._:-]{1,128}$/.test(normalized)) throw new ContractError('AVAILABILITY_POLICY_ID_INVALID', 'Capacity policy ID is invalid'); return new CapacityPolicyId(normalized); } }
export class AvailabilityWindow extends ValueObject<{ readonly startsAt?: string; readonly endsAt?: string }> { private constructor(public readonly startsAt?: Instant, public readonly endsAt?: Instant) { super({ ...(startsAt === undefined ? {} : { startsAt: String(startsAt) }), ...(endsAt === undefined ? {} : { endsAt: String(endsAt) }) }); this.freezeValueObject(); } static from(startsAt?: Instant, endsAt?: Instant): AvailabilityWindow { if (startsAt !== undefined && endsAt !== undefined && String(endsAt) < String(startsAt)) throw new ContractError('AVAILABILITY_WINDOW_INVALID', 'Availability window end must not precede start'); return new AvailabilityWindow(startsAt, endsAt); } includes(at: Instant): boolean { return (this.startsAt === undefined || String(at) >= String(this.startsAt)) && (this.endsAt === undefined || String(at) <= String(this.endsAt)); } }
export type AllocationPolicyValue = 'STRICT' | 'PRIORITY';
export class AllocationPolicy extends ValueObject<{ readonly value: AllocationPolicyValue; readonly adjustment: string }> { private constructor(public readonly value: AllocationPolicyValue, public readonly adjustment: string) { super({ value, adjustment }); this.freezeValueObject(); } static from(value: string, adjustment = '0'): AllocationPolicy { if (value !== 'STRICT' && value !== 'PRIORITY') throw new ContractError('AVAILABILITY_ALLOCATION_POLICY_INVALID', 'Allocation policy is invalid'); return new AllocationPolicy(value, nonNegative(adjustment, 'AVAILABILITY_POLICY_ADJUSTMENT_INVALID')); } adjustmentDecimal(): Decimal { return Decimal.from(this.adjustment); } }
export class ReservationCapacityId extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): ReservationCapacityId { const normalized = value.trim(); if (!/^[A-Za-z0-9._:-]{1,128}$/.test(normalized)) throw new ContractError('AVAILABILITY_RESERVATION_CAPACITY_ID_INVALID', 'Reservation capacity ID is invalid'); return new ReservationCapacityId(normalized); } }
