import { ContractError, ValueObject, type Instant } from '../shared-kernel';
const valid = (v: string, code: string) => { const x = v.trim(); if (!/^[A-Za-z0-9._:-]{1,128}$/.test(x)) throw new ContractError(code, 'Value is invalid'); return x; };
export class StationId extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(v: string): StationId { return new StationId(valid(v, 'KITCHEN_STATION_ID_INVALID')); } }
export class StationRole extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(v: string): StationRole { return new StationRole(valid(v, 'KITCHEN_STATION_ROLE_INVALID')); } }
export type PreparationStatusValue = 'CREATED' | 'QUEUED' | 'ASSIGNED' | 'IN_PROGRESS' | 'PAUSED' | 'COMPLETED' | 'CANCELLED' | 'FAILED';
export class PreparationStatus extends ValueObject<{ readonly value: PreparationStatusValue }> { private constructor(public readonly value: PreparationStatusValue) { super({ value }); this.freezeValueObject(); } static from(v: string): PreparationStatus { const a: readonly PreparationStatusValue[] = ['CREATED', 'QUEUED', 'ASSIGNED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED', 'FAILED']; if (!a.includes(v as PreparationStatusValue)) throw new ContractError('KITCHEN_PREPARATION_STATUS_INVALID', 'Preparation status is invalid'); return new PreparationStatus(v as PreparationStatusValue); } }
export type PreparationPriorityValue = 'NORMAL' | 'RUSH' | 'VIP'; export class PreparationPriority extends ValueObject<{ readonly value: PreparationPriorityValue }> { private constructor(public readonly value: PreparationPriorityValue) { super({ value }); this.freezeValueObject(); } static from(v: string): PreparationPriority { if (v !== 'NORMAL' && v !== 'RUSH' && v !== 'VIP') throw new ContractError('KITCHEN_PRIORITY_INVALID', 'Kitchen priority is invalid'); return new PreparationPriority(v); } }
export class PreparationDuration extends ValueObject<{ readonly milliseconds: number }> { private constructor(public readonly milliseconds: number) { super({ milliseconds }); this.freezeValueObject(); } static milliseconds(v: number): PreparationDuration { if (!Number.isSafeInteger(v) || v < 0) throw new ContractError('KITCHEN_DURATION_INVALID', 'Duration must be a non-negative safe integer'); return new PreparationDuration(v); } }
export class PreparationStepId extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(v: string): PreparationStepId { return new PreparationStepId(valid(v, 'KITCHEN_STEP_ID_INVALID')); } }
export class KitchenReason extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(v: string): KitchenReason { return new KitchenReason(valid(v, 'KITCHEN_REASON_INVALID')); } }
export class ProductionTimelineEntry extends ValueObject<{ readonly status: string; readonly at: string; readonly reason?: string }> { private constructor(public readonly status: string, public readonly at: Instant, public readonly reason?: KitchenReason) { super({ status, at: String(at), ...(reason ? { reason: reason.value } : {}) }); this.freezeValueObject(); } static create(status: string, at: Instant, reason?: KitchenReason): ProductionTimelineEntry { return new ProductionTimelineEntry(status, at, reason); } }
