import { aggregateVersion, correlationId, instant, schemaVersion, tenantId } from '../shared-kernel';
import { checkoutId, type ConfirmedOrderSnapshot, orderId } from '../commerce';
import type { AuthorizedProductionSpecification } from '../inventory-core';
import { productId } from '../catalog-domain';
import { reservationId } from '../reservation';
import { KitchenTicket } from './kitchen.aggregates'; import { KitchenDomainError } from './kitchen.errors'; import { ExecutionValidator, StationRouter } from './kitchen.services'; import { kitchenTicketId } from './kitchen.types'; import { KitchenReason, PreparationPriority, StationId } from './kitchen.value-objects';
const now = instant('2026-07-30T00:00:00.000Z'); const tenant = tenantId('tenant-1');
const order: ConfirmedOrderSnapshot = Object.freeze({ contractVersion: schemaVersion(1), orderId: orderId('order-1'), checkoutId: checkoutId('checkout-1'), tenantId: tenant, orderVersion: aggregateVersion(4), confirmedAt: now, lines: Object.freeze([{ lineId: 'line-1', productId: productId('latte'), requestedQuantity: '1', requestedUnit: 'UNIT' }]), reservationReference: reservationId('reservation-1'), source: 'POS', channel: 'IN_STORE', audit: Object.freeze({ correlationId: correlationId('correlation-1') }) });
const specification: AuthorizedProductionSpecification = Object.freeze({ contractVersion: schemaVersion(1), specificationId: 'latte-v1', productId: productId('latte'), specificationVersion: 1, effectiveVersion: 1, effectiveAt: now, stationAssignments: Object.freeze([{ stationId: 'BAR', stationRole: 'BARISTA', sequence: 1 }]), preparationSteps: Object.freeze([{ stepId: 'brew', sequence: 1, stationId: 'BAR', instruction: 'Brew espresso', estimatedDurationMs: 30000, metadata: Object.freeze({}) }]), metadata: Object.freeze({}) });
const create = () => KitchenTicket.create(tenant, kitchenTicketId('ticket-1'), order, specification, PreparationPriority.from('NORMAL'), now);
describe('Kitchen Execution Domain', () => {
  test('creates deterministic work from immutable public snapshots', () => { const ticket = create(); expect(ticket.tasks).toHaveLength(1); expect(ticket.production.order).not.toBe(order); expect(Object.isFrozen(ticket.production)).toBe(true); expect(new StationRouter().stations(ticket)[0].value).toBe('BAR'); });
  test('executes queued work through assigned, in-progress, and completed states', () => { const ticket = create(); ticket.queue(now); const task = ticket.tasks[0]; ticket.assign(task.id, StationId.from('BAR'), now); ticket.start(now); ticket.completeStep(task.id, now); ticket.complete(now); expect(ticket.status.value).toBe('COMPLETED'); expect(ticket.metrics()).toMatchObject({ totalTasks: 1, completedTasks: 1 }); expect(new ExecutionValidator().validate(ticket)).toBeUndefined(); });
  test('rejects illegal transitions and invalid production station references', () => { const ticket = create(); expect(() => ticket.start(now)).toThrow(KitchenDomainError); ticket.cancel(KitchenReason.from('customer-cancelled'), now); expect(() => ticket.queue(now)).toThrow(KitchenDomainError); const invalid: AuthorizedProductionSpecification = Object.freeze({ ...specification, preparationSteps: Object.freeze([{ ...specification.preparationSteps[0], stationId: 'MISSING' }]) }); expect(() => KitchenTicket.create(tenant, kitchenTicketId('bad-ticket'), order, invalid, PreparationPriority.from('NORMAL'), now)).toThrow(KitchenDomainError); });
});
