import { AggregateRoot, Entity, deepFreeze, type Instant, type TenantId } from '../shared-kernel';
import type { ConfirmedOrderSnapshot } from '../commerce'; import type { AuthorizedProductionSpecification } from '../inventory-core';
import type { KitchenDomainEvent, KitchenEventName, ProductionSnapshot } from './kitchen.contracts'; import { kitchenInvariant } from './kitchen.errors'; import { preparationTaskId, type KitchenTicketId, type PreparationTaskId, type ProductionJobId } from './kitchen.types'; import { KitchenReason, PreparationPriority, PreparationStatus, PreparationStepId, ProductionTimelineEntry, StationId } from './kitchen.value-objects';
const event = (name: KitchenEventName, tenant: TenantId, id: KitchenTicketId, at: Instant): KitchenDomainEvent => ({ name, payload: { tenantId: String(tenant), ticketId: String(id), occurredAt: String(at) } });
export class PreparationTask extends Entity<PreparationTaskId> { private statusValue = PreparationStatus.from('QUEUED'); private assignedStation?: StationId; constructor(id: PreparationTaskId, public readonly stepId: PreparationStepId, public readonly plannedStation: StationId) { super(id); } get status(): PreparationStatus { return this.statusValue; } get station(): StationId | undefined { return this.assignedStation; } assign(station: StationId): void { if (station.value !== this.plannedStation.value) kitchenInvariant('KITCHEN_STATION_ASSIGNMENT_INVALID', 'Task must use its authorized station'); this.assignedStation = station; this.statusValue = PreparationStatus.from('ASSIGNED'); } start(): void { if (this.statusValue.value !== 'ASSIGNED') kitchenInvariant('KITCHEN_TASK_TRANSITION_ILLEGAL', 'Task must be assigned before starting'); this.statusValue = PreparationStatus.from('IN_PROGRESS'); } complete(): void { if (this.statusValue.value !== 'IN_PROGRESS') kitchenInvariant('KITCHEN_TASK_TRANSITION_ILLEGAL', 'Task must be in progress before completion'); this.statusValue = PreparationStatus.from('COMPLETED'); } }
export class ProductionJob extends Entity<ProductionJobId> { constructor(id: ProductionJobId, public readonly ticketId: KitchenTicketId) { super(id); Object.freeze(this); } }
export class StationQueue extends Entity<StationId> { constructor(id: StationId, public readonly taskIds: readonly PreparationTaskId[]) { super(id); this.taskIds = Object.freeze([...taskIds]); Object.freeze(this); } }
export class KitchenExecution extends Entity<KitchenTicketId> { constructor(id: KitchenTicketId, public readonly snapshot: ProductionSnapshot) { super(id); Object.freeze(this); } }
export class KitchenMetrics extends Entity<KitchenTicketId> { constructor(id: KitchenTicketId, public readonly totalTasks: number, public readonly completedTasks: number) { super(id); Object.freeze(this); } }
export class KitchenTicket extends AggregateRoot<KitchenTicketId, KitchenDomainEvent> { private statusValue = PreparationStatus.from('CREATED'); private priorityValue: PreparationPriority; private tasksValue: PreparationTask[]; private timelineValue: ProductionTimelineEntry[] = [];
  private constructor(public readonly tenantId: TenantId, id: KitchenTicketId, public readonly production: ProductionSnapshot, priority: PreparationPriority, tasks: PreparationTask[]) { super(id); this.priorityValue = priority; this.tasksValue = tasks; }
  static create(tenant: TenantId, id: KitchenTicketId, order: ConfirmedOrderSnapshot, specification: AuthorizedProductionSpecification, priority: PreparationPriority, at: Instant): KitchenTicket { if (order.tenantId !== tenant) kitchenInvariant('KITCHEN_TENANT_MISMATCH', 'Kitchen ticket must use one tenant'); const stations = new Set(specification.stationAssignments.map((s) => s.stationId)); if (specification.preparationSteps.some((s) => !stations.has(s.stationId))) kitchenInvariant('KITCHEN_SPECIFICATION_STATION_MISSING', 'Preparation step references no declared station'); const production = deepFreeze({ order: { ...order, lines: order.lines.map((line) => ({ ...line })), audit: { ...order.audit } }, specification: { ...specification, stationAssignments: specification.stationAssignments.map((station) => ({ ...station })), preparationSteps: specification.preparationSteps.map((step) => ({ ...step, metadata: { ...step.metadata } })), metadata: { ...specification.metadata } } }); const tasks = specification.preparationSteps.slice().sort((a, b) => a.sequence - b.sequence).map((step, index) => new PreparationTask(preparationTaskId(`${id}-task-${index + 1}`), PreparationStepId.from(step.stepId), StationId.from(step.stationId))); const ticket = new KitchenTicket(tenant, id, production, priority, tasks); ticket.timelineValue.push(ProductionTimelineEntry.create('CREATED', at)); ticket.record(event('KitchenTicketCreated', tenant, id, at)); return ticket; }
  get status(): PreparationStatus { return this.statusValue; } get priority(): PreparationPriority { return this.priorityValue; } get tasks(): readonly PreparationTask[] { return Object.freeze([...this.tasksValue]); } get timeline(): readonly ProductionTimelineEntry[] { return Object.freeze([...this.timelineValue]); }
  queue(at: Instant): void { this.assert('CREATED'); this.statusValue = PreparationStatus.from('QUEUED'); this.timelineValue.push(ProductionTimelineEntry.create('QUEUED', at)); this.incrementVersion(); }
  assign(taskId: PreparationTaskId, station: StationId, at: Instant): void { if (this.statusValue.value !== 'QUEUED' && this.statusValue.value !== 'ASSIGNED') kitchenInvariant('KITCHEN_TICKET_TRANSITION_ILLEGAL', 'Ticket must be queued to assign stations'); const task = this.task(taskId); task.assign(station); if (this.tasksValue.every((item) => item.status.value === 'ASSIGNED')) this.statusValue = PreparationStatus.from('ASSIGNED'); this.timelineValue.push(ProductionTimelineEntry.create('ASSIGNED', at)); this.incrementVersion(); this.record(event('StationAssigned', this.tenantId, this.id, at)); }
  start(at: Instant): void { this.assert('ASSIGNED'); this.tasksValue.forEach((task) => task.start()); this.statusValue = PreparationStatus.from('IN_PROGRESS'); this.timelineValue.push(ProductionTimelineEntry.create('IN_PROGRESS', at)); this.incrementVersion(); this.record(event('PreparationStarted', this.tenantId, this.id, at)); }
  pause(reason: KitchenReason, at: Instant): void { this.assert('IN_PROGRESS'); this.statusValue = PreparationStatus.from('PAUSED'); this.timelineValue.push(ProductionTimelineEntry.create('PAUSED', at, reason)); this.incrementVersion(); this.record(event('PreparationPaused', this.tenantId, this.id, at)); }
  resume(at: Instant): void { this.assert('PAUSED'); this.statusValue = PreparationStatus.from('IN_PROGRESS'); this.timelineValue.push(ProductionTimelineEntry.create('IN_PROGRESS', at)); this.incrementVersion(); this.record(event('PreparationResumed', this.tenantId, this.id, at)); }
  completeStep(taskId: PreparationTaskId, at: Instant): void { this.assert('IN_PROGRESS'); this.task(taskId).complete(); this.timelineValue.push(ProductionTimelineEntry.create('STEP_COMPLETED', at)); this.incrementVersion(); this.record(event('PreparationStepCompleted', this.tenantId, this.id, at)); }
  complete(at: Instant): void { this.assert('IN_PROGRESS'); if (this.tasksValue.some((task) => task.status.value !== 'COMPLETED')) kitchenInvariant('KITCHEN_TASKS_INCOMPLETE', 'All preparation tasks must be complete'); this.statusValue = PreparationStatus.from('COMPLETED'); this.timelineValue.push(ProductionTimelineEntry.create('COMPLETED', at)); this.incrementVersion(); this.record(event('KitchenTicketCompleted', this.tenantId, this.id, at)); }
  cancel(reason: KitchenReason, at: Instant): void { if (this.statusValue.value === 'COMPLETED' || this.statusValue.value === 'CANCELLED') kitchenInvariant('KITCHEN_TICKET_TERMINAL', 'Terminal ticket cannot be cancelled'); this.statusValue = PreparationStatus.from('CANCELLED'); this.timelineValue.push(ProductionTimelineEntry.create('CANCELLED', at, reason)); this.incrementVersion(); this.record(event('KitchenTicketCancelled', this.tenantId, this.id, at)); }
  reprioritize(priority: PreparationPriority, at: Instant): void { if (this.statusValue.value === 'COMPLETED' || this.statusValue.value === 'CANCELLED') kitchenInvariant('KITCHEN_TICKET_TERMINAL', 'Terminal ticket cannot change priority'); this.priorityValue = priority; this.incrementVersion(); this.record(event('KitchenPriorityChanged', this.tenantId, this.id, at)); }
  metrics(): KitchenMetrics { return new KitchenMetrics(this.id, this.tasksValue.length, this.tasksValue.filter((task) => task.status.value === 'COMPLETED').length); } private task(id: PreparationTaskId): PreparationTask { const task = this.tasksValue.find((item) => item.id === id); if (!task) kitchenInvariant('KITCHEN_TASK_MISSING', 'Preparation task does not exist'); return task; } private assert(status: PreparationStatus['value']): void { if (this.statusValue.value !== status) kitchenInvariant('KITCHEN_TICKET_TRANSITION_ILLEGAL', `Ticket transition requires ${status}`); } }
