import { ContractError, Decimal, ValueObject } from '../shared-kernel';

const requiredText = (value: string, label: string, maximum = 160): string => {
  const normalized = value.trim();
  if (normalized.length === 0 || normalized.length > maximum) throw new ContractError('INVENTORY_TEXT_INVALID', `${label} must contain 1-${maximum} characters`, { label });
  return normalized;
};

export class InventoryItemName extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): InventoryItemName { return new InventoryItemName(requiredText(value, 'InventoryItemName')); } }
export class InventoryCategoryName extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): InventoryCategoryName { return new InventoryCategoryName(requiredText(value, 'InventoryCategoryName', 100)); } }
export class Unit extends ValueObject<{ readonly code: string }> { private constructor(public readonly code: string) { super({ code }); this.freezeValueObject(); } static from(code: string): Unit { const normalized = code.trim().toUpperCase(); if (!/^[A-Z][A-Z0-9_-]{0,31}$/.test(normalized)) throw new ContractError('INVENTORY_UNIT_INVALID', 'Unit must be a 1-32 character uppercase code'); return new Unit(normalized); } }
export class ShelfLife extends ValueObject<{ readonly days: number }> { private constructor(public readonly days: number) { super({ days }); this.freezeValueObject(); } static days(days: number): ShelfLife { if (!Number.isSafeInteger(days) || days < 0 || days > 36_500) throw new ContractError('INVENTORY_SHELF_LIFE_INVALID', 'Shelf life must be between 0 and 36500 days'); return new ShelfLife(days); } }
const positiveDecimal = (value: string, code: string): string => { const decimal = Decimal.from(value); if (decimal.isZero() || decimal.isNegative()) throw new ContractError(code, 'Value must be positive'); return decimal.toString(); };
export class ReorderPoint extends ValueObject<{ readonly value: string; readonly unit: string }> { private constructor(public readonly value: string, public readonly unit: Unit) { super({ value, unit: unit.code }); this.freezeValueObject(); } static from(value: string, unit: Unit): ReorderPoint { return new ReorderPoint(positiveDecimal(value, 'INVENTORY_REORDER_POINT_INVALID'), unit); } }
export class ReorderQuantity extends ValueObject<{ readonly value: string; readonly unit: string }> { private constructor(public readonly value: string, public readonly unit: Unit) { super({ value, unit: unit.code }); this.freezeValueObject(); } static from(value: string, unit: Unit): ReorderQuantity { return new ReorderQuantity(positiveDecimal(value, 'INVENTORY_REORDER_QUANTITY_INVALID'), unit); } }
export class StorageTemperature extends ValueObject<{ readonly celsius: string }> { private constructor(public readonly celsius: string) { super({ celsius }); this.freezeValueObject(); } static celsius(value: string): StorageTemperature { const decimal = Decimal.from(value); if (decimal.compare(Decimal.from('-100')) < 0 || decimal.compare(Decimal.from('100')) > 0) throw new ContractError('INVENTORY_STORAGE_TEMPERATURE_INVALID', 'Storage temperature must be between -100 and 100 Celsius'); return new StorageTemperature(decimal.toString()); } }
export class UnitConversionRatio extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): UnitConversionRatio { return new UnitConversionRatio(positiveDecimal(value, 'INVENTORY_CONVERSION_RATIO_INVALID')); } }
export class WasteReason extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): WasteReason { return new WasteReason(requiredText(value, 'WasteReason', 240)); } }
