import { DateRange, Money, ValueObject, type RoundingStrategy } from '../shared-kernel';
import { InvalidRateError } from './pricing.errors';

export class Price extends ValueObject<{ readonly amount: string; readonly currency: string }> { private constructor(public readonly money: Money) { super(money.serialize()); this.freezeValueObject(); } static from(money: Money): Price { money.assertNonNegative('price'); return new Price(money); } }
export class PricingRate extends ValueObject<{ readonly basisPoints: string }> { private constructor(public readonly basisPoints: bigint) { super({ basisPoints: basisPoints.toString() }); this.freezeValueObject(); } static fromBasisPoints(value: bigint): PricingRate { if (value < 0n || value > 1_000_000n) throw new InvalidRateError(); return new PricingRate(value); } }
export class TaxRate extends ValueObject<{ readonly basisPoints: string }> { private constructor(public readonly value: PricingRate) { super({ basisPoints: value.basisPoints.toString() }); this.freezeValueObject(); } static fromBasisPoints(value: bigint): TaxRate { return new TaxRate(PricingRate.fromBasisPoints(value)); } get basisPoints(): bigint { return this.value.basisPoints; } }
export class DiscountRate extends ValueObject<{ readonly basisPoints: string }> { private constructor(public readonly value: PricingRate) { super({ basisPoints: value.basisPoints.toString() }); this.freezeValueObject(); } static fromBasisPoints(value: bigint): DiscountRate { return new DiscountRate(PricingRate.fromBasisPoints(value)); } get basisPoints(): bigint { return this.value.basisPoints; } }
export class Priority extends ValueObject<{ readonly value: number }> { private constructor(public readonly value: number) { super({ value }); this.freezeValueObject(); } static from(value: number): Priority { if (!Number.isSafeInteger(value)) throw new InvalidRateError(); return new Priority(value); } }
export class PromotionWindow extends ValueObject<{ readonly start: string; readonly end: string }> { private constructor(private readonly range: DateRange) { super(range.serialize()); this.freezeValueObject(); } static from(range: DateRange): PromotionWindow { return new PromotionWindow(range); } contains(at: string): boolean { return this.range.contains(at); } }
export class RoundingPolicy extends ValueObject<{ readonly strategy: RoundingStrategy }> { private constructor(public readonly strategy: RoundingStrategy) { super({ strategy }); this.freezeValueObject(); } static create(strategy: RoundingStrategy = 'HALF_UP'): RoundingPolicy { return new RoundingPolicy(strategy); } }
export class PricingPolicyId extends ValueObject<{ readonly value: string }> { private constructor(public readonly value: string) { super({ value }); this.freezeValueObject(); } static from(value: string): PricingPolicyId { if (!/^[A-Za-z0-9._:-]{1,128}$/.test(value)) throw new InvalidRateError(); return new PricingPolicyId(value); } }
export type RoundingMode = RoundingStrategy; export type PricingStrategy = 'STANDARD'; export type RuleExpression = 'PRODUCT_MATCH'; export type PricingReason = 'BASE_RULE' | 'PROMOTION' | 'TAX' | 'SERVICE_CHARGE';
