import { AggregateRoot, DateRange, DomainEvent, Entity, Money, Quantity, type AggregateId, type Instant, type SupportedCurrencyCode, type TenantId } from '../shared-kernel';
import type { ProductId } from '../catalog-domain';
import { PricingConflictError, PricingStateError } from './pricing.errors';
import { DiscountRate, Price, PricingPolicyId, PricingRate, Priority, PromotionWindow, RoundingPolicy, TaxRate } from './pricing.value-objects';

export type PriceBookId = AggregateId<'PriceBookId'>; export type PriceListId = AggregateId<'PriceListId'>; export type PriceRuleId = AggregateId<'PriceRuleId'>; export type PromotionId = AggregateId<'PromotionId'>; export type DiscountPolicyId = AggregateId<'DiscountPolicyId'>; export type TaxPolicyId = AggregateId<'TaxPolicyId'>; export type ServiceChargePolicyId = AggregateId<'ServiceChargePolicyId'>; export type CurrencyPolicyId = AggregateId<'CurrencyPolicyId'>;
export type PricingEventName = 'PriceBookCreated' | 'PriceBookPublished' | 'PriceBookArchived' | 'PromotionActivated' | 'PromotionExpired' | 'TaxPolicyChanged' | 'DiscountPolicyChanged' | 'PricingRuleChanged';
export type PricingDomainEvent = DomainEvent<PricingEventName, { readonly aggregateId: string; readonly tenantId: string; readonly occurredAt: string }>;
const pricingEvent = (name: PricingEventName, id: string, tenantId: TenantId, at: Instant): PricingDomainEvent => ({ name, payload: { aggregateId: id, tenantId, occurredAt: at } });

export interface PricingScope { readonly tenantId: TenantId; readonly productId?: ProductId; readonly customerSegment?: string; readonly channel?: string; }
export class PricingContext {
  private constructor(public readonly scope: PricingScope, public readonly currency: SupportedCurrencyCode, public readonly occurredAt: Instant) { Object.freeze(this.scope); Object.freeze(this); }
  static create(scope: PricingScope, currency: SupportedCurrencyCode, occurredAt: Instant): PricingContext { return new PricingContext({ ...scope }, currency, occurredAt); }
}

export class PriceRule extends AggregateRoot<PriceRuleId, PricingDomainEvent> {
  private constructor(public readonly tenantId: TenantId, id: PriceRuleId, public readonly productId: ProductId, public readonly price: Price, public readonly priority: Priority, public readonly effective: DateRange | undefined) { super(id); }
  static create(tenantId: TenantId, id: PriceRuleId, productId: ProductId, price: Price, priority: Priority, effective?: DateRange): PriceRule { return new PriceRule(tenantId, id, productId, price, priority, effective); }
  applies(context: PricingContext): boolean { return context.scope.tenantId === this.tenantId && context.scope.productId === this.productId && context.currency === this.price.money.currency.code && (this.effective === undefined || this.effective.contains(context.occurredAt)); }
}

export class PriceList extends AggregateRoot<PriceListId, PricingDomainEvent> { private rules: PriceRule[] = []; private constructor(public readonly tenantId: TenantId, id: PriceListId, public readonly name: string) { super(id); } static create(tenantId: TenantId, id: PriceListId, name: string): PriceList { return new PriceList(tenantId, id, name.trim()); } get items(): readonly PriceRule[] { return Object.freeze([...this.rules]); } addRule(rule: PriceRule): void { if (rule.tenantId !== this.tenantId || this.rules.some((item) => item.id === rule.id)) throw new PricingConflictError('Price rule conflicts with price list'); this.rules.push(rule); this.incrementVersion(); } }

export class PriceBook extends AggregateRoot<PriceBookId, PricingDomainEvent> {
  private rules: PriceRule[] = []; private state: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED' = 'DRAFT';
  private constructor(public readonly tenantId: TenantId, id: PriceBookId, public readonly currency: SupportedCurrencyCode) { super(id); }
  static create(tenantId: TenantId, id: PriceBookId, currency: SupportedCurrencyCode, at: Instant): PriceBook { const book = new PriceBook(tenantId, id, currency); book.record(pricingEvent('PriceBookCreated', id, tenantId, at)); return book; }
  get status(): 'DRAFT' | 'PUBLISHED' | 'ARCHIVED' { return this.state; } get priceRules(): readonly PriceRule[] { return Object.freeze([...this.rules]); }
  addRule(rule: PriceRule, at: Instant): void { if (this.state === 'ARCHIVED') throw new PricingStateError('Archived price books cannot change'); if (rule.tenantId !== this.tenantId || rule.price.money.currency.code !== this.currency || this.rules.some((item) => item.id === rule.id)) throw new PricingConflictError('Price rule conflicts with price book'); this.rules.push(rule); this.incrementVersion(); this.record(pricingEvent('PricingRuleChanged', this.id, this.tenantId, at)); }
  publish(at: Instant): void { if (this.state !== 'DRAFT') throw new PricingStateError('Only draft price books can be published'); this.state = 'PUBLISHED'; this.incrementVersion(); this.record(pricingEvent('PriceBookPublished', this.id, this.tenantId, at)); }
  archive(at: Instant): void { if (this.state === 'ARCHIVED') throw new PricingStateError('Price book is already archived'); this.state = 'ARCHIVED'; this.incrementVersion(); this.record(pricingEvent('PriceBookArchived', this.id, this.tenantId, at)); }
}

export class DiscountPolicy extends AggregateRoot<DiscountPolicyId, PricingDomainEvent> { private constructor(public readonly tenantId: TenantId, id: DiscountPolicyId, public readonly rate: DiscountRate, public readonly priority: Priority, public readonly exclusive: boolean) { super(id); } static create(tenantId: TenantId, id: DiscountPolicyId, rate: DiscountRate, priority: Priority, exclusive: boolean): DiscountPolicy { return new DiscountPolicy(tenantId, id, rate, priority, exclusive); } changed(at: Instant): void { this.incrementVersion(); this.record(pricingEvent('DiscountPolicyChanged', this.id, this.tenantId, at)); } }
export class Promotion extends AggregateRoot<PromotionId, PricingDomainEvent> { private activeValue = false; private constructor(public readonly tenantId: TenantId, id: PromotionId, public readonly discount: DiscountPolicy, public readonly window: PromotionWindow, public readonly scope: PricingScope) { super(id); } static create(tenantId: TenantId, id: PromotionId, discount: DiscountPolicy, window: PromotionWindow, scope: PricingScope): Promotion { return new Promotion(tenantId, id, discount, window, { ...scope }); } get active(): boolean { return this.activeValue; } activate(at: Instant): void { this.activeValue = true; this.incrementVersion(); this.record(pricingEvent('PromotionActivated', this.id, this.tenantId, at)); } deactivate(at: Instant): void { this.activeValue = false; this.incrementVersion(); this.record(pricingEvent('PromotionExpired', this.id, this.tenantId, at)); } applies(context: PricingContext): boolean { return this.activeValue && context.scope.tenantId === this.tenantId && (this.scope.productId === undefined || this.scope.productId === context.scope.productId) && this.window.contains(context.occurredAt); } }
export class TaxPolicy extends AggregateRoot<TaxPolicyId, PricingDomainEvent> { private constructor(public readonly tenantId: TenantId, id: TaxPolicyId, public readonly rate: TaxRate, public readonly inclusive: boolean) { super(id); } static create(tenantId: TenantId, id: TaxPolicyId, rate: TaxRate, inclusive: boolean): TaxPolicy { return new TaxPolicy(tenantId, id, rate, inclusive); } changed(at: Instant): void { this.incrementVersion(); this.record(pricingEvent('TaxPolicyChanged', this.id, this.tenantId, at)); } }
export class ServiceChargePolicy extends AggregateRoot<ServiceChargePolicyId, PricingDomainEvent> { private constructor(public readonly tenantId: TenantId, id: ServiceChargePolicyId, public readonly rate: PricingRate, public readonly priority: Priority) { super(id); } static create(tenantId: TenantId, id: ServiceChargePolicyId, rate: PricingRate, priority: Priority): ServiceChargePolicy { return new ServiceChargePolicy(tenantId, id, rate, priority); } }
export class CurrencyPolicy extends AggregateRoot<CurrencyPolicyId, PricingDomainEvent> { private constructor(public readonly tenantId: TenantId, id: CurrencyPolicyId, public readonly currency: SupportedCurrencyCode) { super(id); } static create(tenantId: TenantId, id: CurrencyPolicyId, currency: SupportedCurrencyCode): CurrencyPolicy { return new CurrencyPolicy(tenantId, id, currency); } }

export interface PricingRequest { readonly productId: ProductId; readonly quantity: Quantity; readonly context: PricingContext; readonly priceBook: PriceBook; readonly promotions: readonly Promotion[]; readonly taxes: readonly TaxPolicy[]; readonly serviceCharges: readonly ServiceChargePolicy[]; readonly rounding: RoundingPolicy; }
export interface AppliedPolicy { readonly id: string; readonly type: 'PRICE_RULE' | 'PROMOTION' | 'TAX' | 'SERVICE_CHARGE'; readonly reason: string; readonly amount: Money; }
export interface ResolvedPrice { readonly productId: ProductId; readonly currency: SupportedCurrencyCode; readonly unitPrice: Money; readonly subtotal: Money; readonly discounts: readonly AppliedPolicy[]; readonly taxes: readonly AppliedPolicy[]; readonly serviceCharges: readonly AppliedPolicy[]; readonly total: Money; readonly trace: readonly string[]; }
export type PricingResult = ResolvedPrice;
