/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm64.node')
          } else {
            nativeBinding = require('@sonex/core-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm-eabi.node')
          } else {
            nativeBinding = require('@sonex/core-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@sonex/core-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@sonex/core-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@sonex/core-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'index.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.darwin-universal.node')
      } else {
        nativeBinding = require('@sonex/core-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'index.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-x64.node')
          } else {
            nativeBinding = require('@sonex/core-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-arm64.node')
          } else {
            nativeBinding = require('@sonex/core-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'index.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.freebsd-x64.node')
      } else {
        nativeBinding = require('@sonex/core-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-musl.node')
            } else {
              nativeBinding = require('@sonex/core-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@sonex/core-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@sonex/core-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@sonex/core-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@sonex/core-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@sonex/core-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@sonex/core-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@sonex/core-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'index.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@sonex/core-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  // Pure JS fallback when native addon binary is not precompiled for current platform
  const computeProductCost = (ingredients, packaging, product_cost, cost_percent) => {
    let ingredient_cost = (!ingredients || ingredients.length === 0)
      ? (product_cost || 0)
      : ingredients.reduce((sum, ing) => {
          const waste_multiplier = 1.0 + (ing.waste_percent || 0) / 100.0;
          return sum + (ing.quantity || 0) * waste_multiplier * (ing.cost_per_unit || 0);
        }, 0);
    let packaging_cost = (packaging || []).reduce((sum, p) => sum + (p.quantity || 0) * (p.cost_per_unit || 0), 0);
    return (ingredient_cost + packaging_cost) * ((cost_percent || 0) / 100.0);
  };

  const computeCostBreakdown = (input) => {
    const ingredient_cost = (input.ingredients || []).reduce((sum, i) => sum + (i.quantity || 0) * (i.cost_per_unit || 0), 0);
    const labor_cost_per_product = (input.total_orders > 0 && input.total_items_sold > 0)
      ? (input.total_labor_cost / input.total_orders) * (input.product_order_count / Math.max(input.total_items_sold, 1))
      : 0;
    const operational_cost_per_product = (input.total_items_sold > 0) ? (input.total_operational_expenses * 0.5) / input.total_items_sold : 0;
    const utility_cost_per_product = (input.total_items_sold > 0) ? input.total_utility_cost / input.total_items_sold : 0;
    const misc_cost_per_product = (input.total_items_sold > 0) ? (input.total_operational_expenses * 0.5) / input.total_items_sold : 0;
    const estimated_cost = ingredient_cost + labor_cost_per_product + operational_cost_per_product + utility_cost_per_product + misc_cost_per_product;
    const estimated_profit = input.selling_price - estimated_cost;
    const profit_margin = input.selling_price > 0 ? (estimated_profit / input.selling_price) * 100 : 0;
    const round2 = (v) => Math.round(v * 100) / 100;
    return {
      product_id: input.product_id,
      product_name: input.product_name,
      selling_price: input.selling_price,
      estimated_cost: round2(estimated_cost),
      estimated_profit: round2(estimated_profit),
      profit_margin: round2(profit_margin),
      ingredient_cost: round2(ingredient_cost),
      ingredient_breakdown: input.ingredients,
      labor_cost: round2(labor_cost_per_product),
      labor_details: {
        total_labor_cost_period: round2(input.total_labor_cost),
        total_orders_in_period: input.total_orders,
        product_order_count: input.product_order_count,
      },
      operational_cost: round2(operational_cost_per_product),
      utility_cost: round2(utility_cost_per_product),
      miscellaneous_cost: round2(misc_cost_per_product),
      date_range: { from: input.date_from, to: input.date_to }
    };
  };

  module.exports.computeProductCost = computeProductCost;
  module.exports.computeCostBreakdown = computeCostBreakdown;
} else {
  const { computeProductCost, computeCostBreakdown } = nativeBinding;
  module.exports.computeProductCost = computeProductCost;
  module.exports.computeCostBreakdown = computeCostBreakdown;
}
